apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
 name: cluster-developer-binding
subjects:
- kind: Group
  name: developers
roleRef:
 kind: ClusterRole
 name: cluster-pod-logs
 apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
 name: cluster-user-reader-binding
subjects:
- kind: Group
  name: cluster-users
roleRef:
 kind: ClusterRole
 name: cluster-pod-reader
 apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
 name: cluster-admin-reader-binding
subjects:
- kind: Group
  name: cluster-admins
roleRef:
 kind: ClusterRole
 name: cluster-pod-reader
 apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
 name: cluster-admin-writer-binding
subjects:
- kind: Group
  name: cluster-admins
roleRef:
 kind: ClusterRole
 name: cluster-pod-writer
 apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
 name: cluster-secrets-binding
subjects:
- kind: Group
  name: secrets-admin
roleRef:
 kind: ClusterRole
 name: cluster-secrets-all-permissions
 apiGroup: rbac.authorization.k8s.io